### ISSUE TITLE
Difficulty in inserting viton band due to poor printing

### ISSUE THREAD

**Issue by orisapir** [rwb27/openflexure_block_stage#10]
Got the stage printed with a lowish quality printer. This is causing the clearance between the horn and the sides to be small and inconsistent so very difficult to get the viton bands through.
Perhaps a narrower insertion tool can help (beyond better print job)

**Comment by rwb27** [comment]
For the record, this is the picture that Ori sent me:
![the band insertion tool](https://user-images.githubusercontent.com/5029703/49997579-de4d2400-ff89-11e8-888e-08c4cb7eeb55.png)
![the printed fibre stage](https://user-images.githubusercontent.com/5029703/49997646-089ee180-ff8a-11e8-8a39-99234c5dc220.png)

From the distortions on overhangs on the tool, I'd guess the printer might either be extruding the part too hot, or not cooling enough with fans, or printing too quickly (my experience is that printing a single small part sometimes results in the time per layer being too short, which means you're printing onto plastic that hasn't fully hardened).  However, I understand you don't have access to try lots of different print settings, so this advice may not be helpful!

The stage, however, looks pretty reasonable to me, as far as I can tell from the outside.  The issues with cooling should be less of a problem here, because the time per layer is much longer.

I have gone through a fair few revisions of the tool in an effort to make it easier to get the bands in, and I must admit I can't remember exactly what version is in the fibre stage repository.  The [version in the microscope repo](https://github.com/rwb27/openflexure_microscope/blob/cantilevered_objective_mount/builds/actuator_assembly_tools.stl) might be better - I think it is longer, which should certainly help.  I can also recommend holding the actuator in place, by using the nut insertion tool in the nut slot (this stops the internal column rising up, and jamming against the top of the column).  Some folk have also had more success putting the bands in one end at a time - that runs a higher risk of snapping them, but gives you more flexibility to wiggle the tool about!

I do have thinner versions of the tool from the past, which might (or might not) help.  I'm happy to dig out some STLs if you are up for giving them a try.  The other suggestion that might help is printing several tools at once (to slow down the print) because that might mean it suffers less from the distortions I can see in your tool.

If you have given up on this print, cracking the top off one of the actuators and taking some photos would be very useful; making the print robust to low quality printing is something I'm very keen on!

All the best, and I hope you get one working soon!

**Comment by rwb27** [comment]
This has now migrated to https://gitlab.com/openflexure/openflexure-block-stage/
