### ISSUE TITLE
OpenSCAD render does not look right

### ISSUE THREAD

**Issue by HazenBabcock** [rwb27/openflexure_block_stage#6]
This is the render that I'm seeing with OpenSCAD 2018.06.05 for base.scad. Any idea what I might have done wrong?

![base_scad](https://user-images.githubusercontent.com/4248614/42343561-70e3886a-8067-11e8-8f67-bd88f1c0df7b.png)

Most of the simpler things such as gears.scad, tools.scad and compact_nut_seat.scad look okay.

**Comment by rwb27** [comment]
Wow, that looks like some serious abstract art!  Two things to check first;
1. Do you have any errors related to the ``use`` directives or ``include`` directive?  Missing includes can cause wierd things, though usually it's missing geometry rather than garbage.
2. Are you using "preview" (F5) or "render" (F6)?  I've found the former to be extremely unreliable for all but the simplest of models.

**Comment by HazenBabcock** [comment]
It looks like the problem is (2). When OpenSCAD starts I guess it automatically shows you "preview". The model looks fine once you render it. Thanks!
